import Head from "next/head";
import Image from "next/image";
import styles from "../styles/page.module.css";
import background from "../assets/background.jpg";
import Navbar from "../components/nav/Navbar";
export default function Home() {
  const { videos, container, backgroundContainer } = styles;
  return (
    <>
      <Head>
        <title>Colaps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={container}>
        <div className={backgroundContainer}>
          <Image
            objectFit="cover"
            alt="card pic"
            layout="fill"
            src={background}
          />
        </div>

        <h1>Colaps</h1>

        <div className={videos}>
          <iframe
            width="620"
            height="415"
            src="https://www.youtube.com/embed/bhGN_bDotBw?autoplay=0"
          />
          <iframe
            width="620"
            height="415"
            src="https://www.youtube.com/embed/t_ppjQkVzWI?autoplay=0"
          />
          <iframe
            width="620"
            height="415"
            src="https://www.youtube.com/embed/1MPDVxYE_4w?autoplay=0"
          />
        </div>
      </main>
    </>
  );
}
