import Head from "next/head";
import Navbar from "../components/Navbar";
import Section from "../components/Section";
import dlow from "../assets/dlow.jpg";
import colaps from "../assets/colaps.jpg";
import codfish from "../assets/codfish.jpg";
import bart from "../assets/b-art.jpg";
import river from "../assets/river.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Boots N Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <Section reference={"/dlow"} background={dlow} />
        <Section reference={"/colaps"} background={colaps} />
        <Section reference={"/codfish"} background={codfish} />
        <Section reference={"/b-art"} background={bart} />
        <Section reference={"/river"} background={river} />
      </main>
    </div>
  );
}
